# Docker Compose para API comandas_do_ze
services:
  # Serviço do banco de dados MySQL
  db:
    image: mysql:8
    container_name: mysql_comandas_api
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME} # cria o database na primeira inicialização
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$DB_PASS"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
    networks:
      - comandas_network
  # Serviço da API FastAPI com Hypercorn e QUIC
  comandas_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: uniplac-victorcunha/comandas-api:latest
    container_name: comandas_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env # carrega as variáveis de ambiente do arquivo .env
    environment:
      TESTE_AMBIENTE: "API DO ZÉ"
    ports:
      - "${PORT}:4443/tcp" # https
      - "${PORT}:4443/udp" # quic/http/3
    volumes:
      - ./cert:/cert:ro # copia os certificados de cert para o container
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - comandas_network
# Volumes persistentes
volumes:
  db_data:
    driver: local
# Rede personalizada
networks:
  comandas_network:
    name: comandas_network_prod
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
