# Victor da Cunha
### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome" : "Victor da Cunha",
    "cpf" : "12345678901",
    "telefone" : "49988765432"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
Content-Type: application/json

{
    "nome" : "Victor da Cunha EDIT",
    "cpf" : "12345678901",
    "telefone" : "49988765432"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1
