# Victor da Cunha
### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1
### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome" : "Pastel de Carne",
    "descricao" : "Pastel frito com recheio de carne moida",
    "foto" : null,
    "valor_unitario" : 12.50
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
Content-Type: application/json

{
    "nome" : "Pastel de Queijo EDIT",
    "descricao" : "Pastel frito com recheio de queijo",
    "foto" : null,
    "valor_unitario" : 10.00
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1
